language: python
python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then pip install codecov; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then make test-cover; else make test; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 2* ]]; then codecov; fi
