language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4* ]]; then pip install codecov; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4* ]]; then make test-cover; else make test; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4* ]]; then codecov; fi
