dist: bionic
language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
install:
  - pip install nose2
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7* ]]; then pip install codecov; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7* ]]; then nose2 -C --coverage skoolkit; else nose2; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.7* ]]; then codecov; fi
