language: python
python:
  - 3.4
  - 3.5
  - 3.6
install:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4* ]]; then pip install codecov; fi
script:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4* ]]; then nosetests -w tests --with-coverage --cover-package=skoolkit; else nosetests -w tests; fi
after_success:
  - if [[ $TRAVIS_PYTHON_VERSION == 3.4* ]]; then codecov; fi
