name: coverage

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install nose2 and codecov
      run: |
        python -m pip install --upgrade pip
        python -m pip install nose2 codecov
    - name: Run tests with coverage
      run: |
        nose2 -C --coverage skoolkit
        codecov
